# Generated by Django 5.1.1 on 2024-12-16 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True, verbose_name='Nombre de la Institución')),
            ],
        ),
        migrations.CreateModel(
            name='Inscrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Inscrito')),
                ('nro_personas', models.PositiveSmallIntegerField(verbose_name='Número de Personas')),
                ('telefono', models.CharField(max_length=15, verbose_name='Teléfono de Contacto')),
                ('fecha_inscripcion', models.DateField(auto_now_add=True, verbose_name='Fecha de Inscripción')),
                ('hora_inscripcion', models.TimeField(auto_now_add=True, verbose_name='Hora de Inscripción')),
                ('estado', models.CharField(choices=[('RESERVADO', 'Reservado'), ('COMPLETADA', 'Completada'), ('ANULADA', 'Anulada'), ('NO_ASISTEN', 'No Asisten')], default='RESERVADO', max_length=12, verbose_name='Estado')),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observación')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gut_Ema_FINAL_APP.institucion', verbose_name='Institución')),
            ],
        ),
    ]
